title: Chatbotman
subtitle: "The Ultimate platform to develop intelligent chatbot"
description: "Further description of chatbotman"
author: Chatbotman Ltd
language: en
timezone: Asia/Hong_Kong

url: https://docs.chatbotman.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:chatbotman/chatbotman.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
facebook: thechatbotman
github: chatbotman/chatbotman
